COLUMNS:
  sex: int32
  age: int32
  education: int32
  smokingStatus: int32
  cigsPerDay: int32
  BPMeds: int32
  prevalentStroke: int32
  prevalentHyp: int32
  diabetes: int32
  totChol: int32
  sysBP: float32
  diaBP: float32
  BMI: float32
  heartRate: int32
  glucose: int32


TARGET_COLUMN:
  name: CHDRisk
